// Package reference: the plug hollowed with a genuine 1.0 mm wall.
//
// The only trustworthy way to offset a swept solid is to offset the 2D
// PROFILE and sweep the offset profile with the SAME height and twist. The
// inner surface is then the true 1.0 mm inward offset of the outer surface
// at every height, because both surfaces are generated by the same twist
// map from profiles that are exactly 1.0 mm apart in profile space.
//
// Scalar 3D offsets (Shrink/Grow/Offset) are NOT Euclidean on a twisted
// solid: TwistExtrude3D multiplies its returned distance by
// invStretch = 1/sqrt(1 + k^2 * rMax^2), k = twist/height, to keep the
// octree renderer from skipping cells. Here k = pi/20 and rMax^2 = 5^2+3^2
// = 34, so invStretch = 1/1.3560. A nominal Shrink(1.0) therefore insets
// 1.356 mm of real profile-space material, not 1.0 - a 36 percent error -
// and it insets the TOP cap by the same 1.356 mm, capping the bore the user
// asked to be open.
//
// Incident: mcweed memory note feedback_fluent_api.md, 2026-08-28: "Shrink /
// Grow on TwistExtrude'd (or otherwise warped) solids are NOT Euclidean
// offsets ... a nominal 0.37 Shrink removed >1mm of real geometry. Offsets
// on swept solids must be done in PROFILE space (2D offset before the
// sweep)." Same root cause as mined2 I-11, where a 0.5 mm chamfer on a
// twisted pill pinched the whole 1.5 mm section to a peak.
package reference

import (
	"github.com/snowbldr/fluent-sdfx/shape"
	"github.com/snowbldr/fluent-sdfx/solid"
	v2 "github.com/snowbldr/fluent-sdfx/vec/v2"
	v3 "github.com/snowbldr/fluent-sdfx/vec/v3"
)

const (
	profX     = 10.0
	profY     = 6.0
	profRound = 1.0
	plugH     = 20.0
	twistDeg  = 180.0

	wallT  = 1.0               // wall thickness, everywhere
	floorT = 2.0               // solid floor at the bottom
	zFloor = -plugH/2 + floorT // -8: top of the floor, where the bore starts
)

func Build() *solid.Solid {
	profile := shape.Rect(v2.XY(profX, profY), profRound)
	plug := profile.TwistExtrude(plugH, twistDeg)

	// Inner void: the profile offset inward by the wall thickness, swept
	// with the SAME height and twist, then trimmed to start at the floor.
	// Its top cap coincides with the plug top, so the bore is open there.
	bore := profile.Offset(-wallT).TwistExtrude(plugH, twistDeg).
		CutPlane(v3.Z(zFloor), v3.Z(1))

	return plug.Cut(bore)
}
